// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Rui.Issue.Reproduce
{
	public partial class MyWindowController : NSWindowController
	{
		public MyWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
